language: rust

matrix:
  include:

    ####### linux

    - name: linux|stable|no-default
      os: linux
      rust: stable
      env: FEATURE_FLAGS="--no-default-features"
      cache: cargo
      addons:
        apt:
          packages:
            - libgraphite2-dev

    - name: linux|stable|pkg-config
      os: linux
      rust: stable
      env: FEATURE_FLAGS="--no-default-features --features pkg-config"
      cache: cargo
      addons:
        apt:
          packages:
            - libgraphite2-dev

    - name: linux|stable|static
      os: linux
      rust: stable
      env: FEATURE_FLAGS="--no-default-features --features static"
      cache: cargo

    - name: linux|nightly|default
      os: linux
      rust: nightly
      cache: cargo

    ####### osx

    - name: osx|stable|no-default
      os: osx
      rust: stable
      env: FEATURE_FLAGS="--no-default-features"
      cache: cargo
      addons:
        homebrew:
          packages:
            - graphite2

    - name: osx|stable|pkg-config
      os: osx
      rust: stable
      # Use newest image to get the latest formula.
      osx_image: xcode10.2
      env: FEATURE_FLAGS="--no-default-features --features pkg-config"
      cache: cargo
      addons:
        homebrew:
          packages:
            - graphite2

    - name: osx|stable|static
      os: osx
      rust: stable
      env: FEATURE_FLAGS="--no-default-features --features static"
      cache: cargo

    - name: osx|nightly|default
      os: osx
      rust: nightly
      cache: cargo

    ####### windows

    # Do not use `cache: cargo` for windows.
    # See https://github.com/travis-ci/casher/pull/38#issuecomment-486544019

    - name: windows|stable|vcpkg|shared
      os: windows
      rust: stable-x86_64-pc-windows-msvc
      env:
        FEATURE_FLAGS="--no-default-features --features vcpkg"
        VCPKG_DEFAULT_TRIPLET=x64-windows
        VCPKGRS_DYNAMIC=1
        VCPKG_ROOT=$HOME/vcpkg
      install:
        - bash ./.travis/install-vcpkg.sh

    - name: windows|stable|vcpkg|static
      os: windows
      rust: stable-i686-pc-windows-msvc
      env:
        FEATURE_FLAGS="--no-default-features --features vcpkg"
        VCPKG_DEFAULT_TRIPLET=x86-windows-static
        RUSTFLAGS=-Ctarget-feature=+crt-static
        VCPKG_ROOT=$HOME/vcpkg
      install:
        - bash ./.travis/install-vcpkg.sh

    - name: windows|stable|default
      os: windows
      rust: nightly

script:
  # Package a crate and verify it by building with the given feature flags
  - cargo package -vv $FEATURE_FLAGS
