language: rust
cache: cargo

matrix:
  include:

    ####### linux

    - name: linux|stable|no-default
      os: linux
      rust: stable
      env: FEATURE_FLAGS="--no-default-features"
      addons:
        apt:
          packages:
            - libgraphite2-dev

    - name: linux|stable|pkg-config
      os: linux
      rust: stable
      env: FEATURE_FLAGS="--no-default-features --features pkg-config"
      addons:
        apt:
          packages:
            - libgraphite2-dev

    - name: linux|stable|static
      os: linux
      rust: stable
      env: FEATURE_FLAGS="--no-default-features --features static"

    - name: linux|nightly|default
      os: linux
      rust: nightly

    ####### osx

    - name: osx|stable|no-default
      os: osx
      rust: stable
      env: FEATURE_FLAGS="--no-default-features"
      addons:
        homebrew:
          packages:
            - graphite2

    - name: osx|stable|pkg-config
      os: osx
      rust: stable
      # Use newest image to get the latest formula.
      osx_image: xcode10.2
      env: FEATURE_FLAGS="--no-default-features --features pkg-config"
      addons:
        homebrew:
          packages:
            - graphite2

    - name: osx|stable|static
      os: osx
      rust: stable
      env: FEATURE_FLAGS="--no-default-features --features static"

    - name: osx|nightly|default
      os: osx
      rust: nightly

before_script:
  # Download all dependencies
  - cargo fetch

script:
  # Build and test the package with the given feature flags
  - cargo build -vv $FEATURE_FLAGS
  - cargo package -vv $FEATURE_FLAGS
